### PR TITLE
Add Fetch/FetchOK convenience functions to retrieve deeply nested values

### PR DESCRIPTION
**Pull request by renier**
Alleviates #22, @JunliWang.

### CODE REVIEW

**Comment by riethm** [comment]
I'm not totally sold on the name 'Fetch'.  Sounds too much like a database operation (one could be forgiven for assuming that fields will be automatically retrieved from SoftLayer as needed, when in-fact, they are just being read from an already-populated struct).  'Read'?  'SafeDeref'?  Something else?

**Comment by renier** [comment]
@riethm more or less like a database/remote retrieve operation than `Get`?

**Comment by renier** [comment]
@riethm How about _Grab_ or _Take_?

**Comment by riethm** [comment]
Yes.

**Comment by renier** [comment]
Changed to `Grab` and `GrabOk`.

**Pull request merged**
